name: Rules

on:
  schedule:
    - cron: "10 10 1-31/2 * *"
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          rm -fr * .git .github
          wget -q https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geoip.dat &> /dev/null
          wget -q https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geosite.dat &> /dev/null


          echo -e "|    Size   |     DL  | sha512sum |\n|  ---  |  ---  |  ---  |" > README.md
          shopt -s extglob
          for file in $(ls !(*.md)); do
            echo "| $(expr $(wc -c < $file )  / 1000000  | numfmt --to=iec-i --suffix=MB --format="%f") | [$file](https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/$file) | $(sha512sum  $file | cut -d " " -f1 ) |" >> README.md
          done



          mkdir -p .github/workflows
          wget -qO .github/workflows/Backup.yml https://github.com/${{ github.repository }}/raw/main/.github/workflows/Backup.yml &> /dev/null

          git config --global init.defaultBranch main
          git init
          git add .
          git config user.name "googleians"
          git config user.email "77716481+googleians@users.noreply.github.com"
          git commit -m "binary of v2ray-core for windows 10 Pro amd64 "
          git tag -a "$(date +"%d-%m-%Y")" -m "$(date +"%d-%m-%Y")"
          git remote add release "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -u --follow-tags release main -f
